agent_id: microtestflinger-agent-01
server_address: http://127.0.0.1:5000
polling_interval: 5

job_queues:
  - megademo

execution_basedir: /tmp/microtestflinger/run
logging_basedir: /tmp/microtestflinger/logs
results_basedir: /tmp/microtestflinger/results
logging_level: DEBUG

provision_command: "testflinger-device-connector qemu_connector provision -c /tmp/microtestflinger/qemu-device.yaml testflinger.json"
setup_command: "QEMU_CONNECTOR_PHASE=setup testflinger-device-connector qemu_connector runtest -c /tmp/microtestflinger/qemu-device.yaml testflinger.json"
test_command: "QEMU_CONNECTOR_PHASE=test testflinger-device-connector qemu_connector runtest -c /tmp/microtestflinger/qemu-device.yaml testflinger.json"
cleanup_command: "testflinger-device-connector qemu_connector cleanup -c /tmp/microtestflinger/qemu-device.yaml testflinger.json"
